const { getServerOTP, getUserEmail } = require("./sendOtp");
const colors = require("colors");
const jwt = require("jsonwebtoken");
require("dotenv").config();

const validateOtpForLogin = async (req, res) => {
  const userOTP = req.body.otpInput;
 
  const serverOTP = await getServerOTP(); 

  console.log(`user otp --> ${userOTP}`);
  console.log(`server otp --> ${serverOTP}`);
  console.log(`user email --> ${await getUserEmail()}`);

  const validate = userOTP === serverOTP;

  if (validate) {
    console.log(`otp entered by the user ${userOTP}`);
    console.log(`otp generated by the server ${serverOTP}`);

    const payload = { email: await getUserEmail() };
    const token = jwt.sign(payload, process.env.SECRETKEY);

    res.json({ msg: "Success", token });
  } else {
    res.json({ msg: "Failure" });
    console.log("Sorry wrong OTP entered");
  }
};

module.exports = validateOtpForLogin;
