const validateOtpForLogin = (req,res)=>{
    const otpEnteredByUser = req.body.otp;
    const serverGeneratedOtp = localStorage.getItem("userOtp");
    console.log(otpEnteredByUser);
    console.log(serverGeneratedOtp);
    const validate = otpEnteredByUser === serverGeneratedOtp ? true : false;
    if(validate){
        console.log(`otp entered by the user ${otpEnteredByUser}`);
        console.log(`otp generated by the server ${otp}`);
        res.json({msg: 'login successful'});
    } else{
        res.json({msg: 'failed to log in'});
        console.log('There\'s an error while logged in to your account');
    }
}

module.exports = validateOtpForLogin;